language: go
go:
    - 1.7
services:
    - docker
install:
    - go get -u -t -v ./...
    - go get github.com/golang/lint/golint golang.org/x/tools/cmd/goimports github.com/onsi/ginkgo/ginkgo
scripts:
    - diff <(gofmt -d .) <(echo -n)
    - go vet -x ./...
    - golint ./...
    - ginkgo -r --randomizeAllSpecs --randomizeSuites --failOnPending --cover --trace --race --progress
after_success:
    - bash <(curl -s https://codecov.io/bash) -f "*.coverprofile" -s ".;./lib" -X coveragepy -Z
    - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o counter-test .;
    - if [ "$TRAVIS_BRANCH" == "master" ]; then
        docker build -t zeta0/go-travis-docker-test .; 
        docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
        docker push zeta0/go-travis-docker-test;
        fi
    - test -n "$TRAVIS_TAG" && curl -s https://raw.githubusercontent.com/goreleaser/get/master/latest | bash